name: Move JPG Files

on:
  workflow_dispatch:
  schedule:
    - cron:  '10 */2 * * *'

jobs:
  update-index-html:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout code
      uses: actions/checkout@v3
      with:
        ref: nil

    - name: Auto commit
      run: |  
          mv -f *.jpg ./nasa
          if [[ -n $(git status -s) ]]; then
            git config --local user.email "fangling@outlook.com"
            git config --local user.name "caaby"
            # git remote set-url origin https://${{ github.actor }}:${{ secrets.GITHUB_TOKEN }}@github.com/${{ github.repository }}
            git add .
            git commit -am "change coloud config"
            git push
          else
            echo "No changes to commit"
          fi
