name: 每日更新nasa图片

on:
  workflow_dispatch:
  schedule:
    - cron:  '15 */7 * * *'

jobs:
  append-logs:
    runs-on: ubuntu-latest
    steps:
    - name: Clone repository
      uses: actions/checkout@v3
      with:
        ref: nil
        
    - name: Auto commit
      run: |
          git config --local user.email "fangling@outlook.ie"
          git config --local user.name "imgl"
          git remote set-url origin https://${{ github.actor }}:${{ secrets.GITHUB_TOKEN }}@github.com/${{ github.repository }}
          cd ./nasa
          bash <(curl -sSL https://gist.githubusercontent.com/caaby/5e6d979789ce46bb7b6f277eda76549a/raw/nasa.sh)
          git add .
          git commit --allow-empty -am "add nasa image"
          git push
